version: "3"
services:
  ms-user-repo-docker:
    image: ms-user-repo-docker
    ports:
      - "9000:9191"
  ms-file-mgmt-docker:
    image: ms-file-mgmt-docker
    ports:
      - "8000:8181"
  db:
    image: postgres:9.3.6
    volumes: 
      - /home/sj/storage-poc/local-data-for-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: asecurepassword
    ports:
      - "5434:5432"

